- name: demo on conditions
  hosts: local
  connection: local
  vars:
   IS_LIVE: true
  tasks:
  - name: check live or not
    ansible.builtin.debug:
      msg: "This is live environment"
    when: IS_LIVE
