- name: demo on conditions
  hosts: local
  connection: local
  vars:
    IS_LIVE: false
  tasks:
  - name: check live or not
    ansible.builtin.debug:
      msg: "This is live environment make sure to be careful"
    when: IS_LIVE